sudo: required

dist: xenial

services:
    - docker

env:
    - CHANGE_MINIKUBE_NONE_USER=true GO111MODULE=on

language: java
jdk: openjdk8

before_script:
    #install kubectl and minikube
    - yum install epel-release
    - yum install conntrack-tools
    - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
    - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
    - sudo minikube start --vm-driver=none --kubernetes-version=v1.18.0
    - minikube update-context
    - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
    - docker run --rm -d -it -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 --name chaos-mysql-5.6 mysql:5.6 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time_zone='+8:00'
    - docker exec -i chaos-mysql-5.6 -uroot -p123456 < sql/chaos-platform.sql

script:
    - kubectl cluster-info
    - mvn test

after_success:
  - bash <(curl -s https://codecov.io/bash)
